if ( GetLocale() == "zhCN" ) then 
	FRIENDS_MENU_XP_CANNOT_TARGET = "无法选定<$name$>为目标。"

	FMXP_BUTTON_ADD_FRIEND = "添加好友"
	FMXP_BUTTON_SEND_WHO = "查询详情"
	FMXP_BUTTON_ADD_GUILD = "公会邀请"
	FMXP_BUTTON_GET_NAME = "复制名字"
	FMXP_BUTTON_TRADE = "交易"
	FMXP_BUTTON_GUILD_LEAVE = "退出公会"
	FMXP_BUTTON_GUILD_PROMOTE = "提升该会员"
	FMXP_BUTTON_PVP_REPORT_AFK = "举报玩家"
	FMXP_BUTTON_SET_FOCUS = "设为焦点"
	FMXP_BUTTON_PROMOTE = "提升为队长"
	FMXP_BUTTON_LOOT_PROMOTE = "设为拾取者"
	FMXP_BUTTON_ACHIEVEMENTS = "比较成就"
	FMXP_BUTTON_ARMORY = "英雄榜"
end