QulightL = { }

-- general
	QulightL.option_general = "General"
	QulightL.option_general_uiscale = "Auto UI Scale"
	QulightL.option_general_multisample = "Multisample protection (clean 1px border)"
	QulightL.option_general_customuiscale = "UI Scale (if auto-scale is disabled)"
	QulightL.option_general_AutoRepair = "Auto Repair items"
	QulightL.option_general_AutoGreed = "Auto Greed"												
	QulightL.option_general_AutoDisenchant = "Auto Disenchant"	
	QulightL.option_general_AutoAcceptInvite = "Enable Auto-Invite (Friends and Guildmates)"
	QulightL.option_general_BlizzardsErrorFrameHiding = "Hide spamming error at the middle of your screen"
	QulightL.option_general_topbottompanel = "Top/Bottom panels"
	QulightL.option_general_autoinvite = "Autoinvite"
	QulightL.option_general_centerpanel = "Left, Right DPS Info Stats"
	
	-- Unitframes
	QulightL.option_unitframes = "Unit Frames"
	QulightL.option_unitframes_enable = "Enable Unit Frames"
 	QulightL.option_unitframes_HealFrames = "Raid Frames" 
	QulightL.option_unitframes_showIndicators = "Buffs Indicator" 
	QulightL.option_unitframes_showAuraWatch = "Show buffs in corners" 
	QulightL.option_unitframes_ShowParty = "Show party frames (shown as 5man raid)" 
	QulightL.option_unitframes_ShowRaid = "Show raid frames" 
	QulightL.option_unitframes_RaidShowSolo = "Show raid frames even when solo" 
	QulightL.option_unitframes_RaidShowAllGroups = "Show raid groups 6, 7 and 8 (more than 25man raid)" 
	QulightL.option_unitframes_enableDebuffHighlight = "Enable *dispelable* debuff highlight for raid frames" 
	QulightL.option_unitframes_showRaidDebuffs = "Enable important debuff icons to show on raid units" 
	QulightL.option_unitframes_showtot = "Show target of target frame" 
	QulightL.option_unitframes_showpet = "Show pet frame" 
	QulightL.option_unitframes_showfocus = "Show focus frame" 
	QulightL.option_unitframes_showfocustarget = "Show focus target frame" 
	QulightL.option_unitframes_showBossFrames = "Show boss frame" 
	QulightL.option_unitframes_TotemBars = "Show Totem Bars"
	QulightL.option_unitframes_MTFrames = "Show main tank frames" 
	QulightL.option_unitframes_ArenaFrames = "Show arena frame" 
	QulightL.option_unitframes_Reputationbar = "Show Reputation bar" 
	QulightL.option_unitframes_Experiencebar = "Show Experience bar" 
	QulightL.option_unitframes_showPlayerAuras = "use a custom player buffs/debuffs frame instead of Blizzard's default" 
	QulightL.option_unitframes_ThreatBar = "Show Threat bar"
	QulightL.option_unitframes_showPortrait = "Show Portrait on player and target frames"
	QulightL.option_unitframes_showRunebar = "Show DK rune bar"
	QulightL.option_unitframes_showHolybar = "Show Paladin HolyPower bar" 
	QulightL.option_unitframes_showEclipsebar = "Show druid Eclipse bar" 
	QulightL.option_unitframes_showShardbar = "Show Warlock SoulShard bar" 
	QulightL.option_unitframes_RCheckIcon = "Show raid check icon" 
	QulightL.option_unitframes_Castbars = "Use built-in castbars" 
	QulightL.option_unitframes_showLFDIcons = "Show dungeon role icons in raid/party"
   	QulightL.option_unitframes_HealthcolorClass = "Health color class"
	QulightL.option_unitframes_Powercolor = "Power bar by power color oO"
	QulightL.option_unitframes_showPartyFrames	 = "Show party frames"
	QulightL.option_unitframes_bigcastbar = "Big castbar"
	QulightL.option_unitframes_widthbigcastbar = "Width big castbar"
	QulightL.option_unitframes_heightbigcastbar = "Height big castbar"
	
	--raidframes
	QulightL.option_raidframes = "Raid Frames"
	-- Main
	QulightL.option_raidframes_aggro_border = "Aggro border"
	QulightL.option_raidframes_deficit_health = "Raid deficit health"
	QulightL.option_raidframes_power = "Power bar"
	QulightL.option_raidframes_vertical_health = "Vertical orientation of health"
	QulightL.option_raidframes_alpha_health = "Alpha of healthbars when 100%hp"
	QulightL.option_raidframes_show_range = "Show range opacity for raidframes"
	QulightL.option_raidframes_range_alpha = "Alpha of unitframes when unit is out of range"
	QulightL.option_raidframes_hp_value = "HP text"
	QulightL.option_raidframes_width = "Width"
	QulightL.option_raidframes_height = "Height"
	QulightL.option_raidframes_show_party = "Show party frames"
	QulightL.option_raidframes_show_raid = "Show raid frames"
	QulightL.option_raidframes_solo_mode = "Show player frame always"
	QulightL.option_raidframes_player_in_party = "Show player frame in party"
	QulightL.option_raidframes_raid_groups = "Number of groups in raid"
	QulightL.option_raidframes_raid_groups_vertical = "Vertical raid groups"
	QulightL.option_raidframes_icons_role = "Role icon on frames"
	QulightL.option_raidframes_icons_raid_mark = "Raid marks"
	QulightL.option_raidframes_icons_ready_check = "Ready check icons"
	QulightL.option_raidframes_icons_leader = "Leader icon, assistant icon, master loot icon on frames"
	QulightL.option_raidframes_plugins_debuffhighlight_icon = "Debuff highlight texture + icon"
	QulightL.option_raidframes_plugins_aura_watch = "Raid debuff icons"
	QulightL.option_raidframes_plugins_aura_watch_timer = "Timer on raid debuff icons"
	QulightL.option_raidframes_plugins_healcomm = "Show incoming heal on frame"
	QulightL.option_raidframes_plugins_auto_resurrection = "Auto cast resurrection on middle click when the unit is dead (doesn't work with Clique enabled)"
	QulightL.option_raidframes_own_color = "Set your color for health bars"
	QulightL.option_raidframes_fontsize = "Font size"
   	QulightL.option_raidframes_fontsizeEdge = "Add Font size"
 	QulightL.option_raidframes_outline = "Font style"
	QulightL.option_raidframes_bar_color_value = "Health bar color by current health remaining"
	QulightL.option_raidframes_color_value = "Health/mana value is colored"
	QulightL.option_raidframes_plugins_smooth_bar = "Smooth bar"
	QulightL.option_raidframes_show_timer = "Show cooldown timer on aura icons"
	QulightL.option_raidframes_show_spiral = "Spiral on aura icons"
	QulightL.option_raidframes_debuff_color_type = "Color debuff by type"
	
	--media
	QulightL.option_media = "Media" 	
	QulightL.option_media_font = "main font for Qulight UI" 
	QulightL.option_media_pxfont = "1 px font for Qulight UI" 
	QulightL.option_media_fontsize = "Size of font " 
	QulightL.option_media_bordercolor = "Border color" 
	QulightL.option_media_backdropcolor = "Background color" 
	QulightL.option_media_texture = "Texture" 
	QulightL.option_media_blank = "Background Texture" 
	--bags
	QulightL.option_bags = "Bags"	
	QulightL.option_bags_Enable = "Enable all in one bag"
	QulightL.option_bags_BagBars = "Enable bags panel"
	--datatext
	QulightL.option_datatext = "Data Text"
	QulightL.option_datatext_Durability = "Durability position (0 for disabled)"	
	QulightL.option_datatext_System = "Latency and FPS position (0 for disabled)"
	QulightL.option_datatext_Gold = "Gold position (0 for disabled)"
	QulightL.option_datatext_Guild = "Guild position (0 for disabled)"
	QulightL.option_datatext_Friends = "Friends position (0 for disabled)"
	QulightL.option_datatext_Bags = "Bags position (0 for disabled)"
	QulightL.option_datatext_Wowtime = "Time position (0 for disabled)"
	QulightL.option_datatext_Togglemenu = "ToggleMenu"
	QulightL.option_datatext_specswitcher = "Spec switcher"
	QulightL.option_datatext_Time24 = "Enable 24h time"
	QulightL.option_datatext_Localtime = "Use Local Time instead of Server Time"
	QulightL.option_datatext_classcolor = "Class color data text"
	QulightL.option_datatext_color = "If Class color data text false then choose color: "
	QulightL.option_datatext_power = "Attack Power\Spell Power position (0 for disabled)"
	QulightL.option_datatext_mastery = "Mastery position (0 for disabled)"
	QulightL.option_datatext_haste = "Haste position (0 for disabled)"
	QulightL.option_datatext_crit = "Crit position (0 for disabled)"
	QulightL.option_datatext_dps = "DPS position (0 for disabled)"
	QulightL.option_datatext_hps = "HPS position (0 for disabled)"
	QulightL.option_bags_bankcolumns = "The number of cells in the row"
	QulightL.option_bags_buttonsize = "Cell Size"
	QulightL.option_bags_buttonspace = "Space Between Cells"
	--loot
	QulightL.option_loot = "Loot"
	QulightL.option_loot_lootframe = "Enable loot window"
	QulightL.option_loot_rolllootframe = "Enable item roll window"
	QulightL.option_loot_position = "Позиция окна розыгрыша"
	--misk
	QulightL.option_enable = "Enable" 
	QulightL.option_armory_link = "Enable Armory Link (Then dont work Maintank and aimer)"
	QulightL.option_addonmanager = "Addon Manager" 
	QulightL.option_togglemenu = "Toggle menu" 
	QulightL.option_togglemenu_buttonwidth = "Button width" 
	QulightL.option_togglemenu_buttonheight = "Button height" 
	QulightL.option_togglemenu_classcolor = "Classcolor border" 
	QulightL.option_classtimer = "Class Timer" 
	QulightL.option_cooldown = "Cooldown" 
	QulightL.option_skinframe = "Skinframe" 	
	QulightL.option_filger = "Filger" 
	QulightL.option_Threatbar = "Threatbar" 
	--chat
	QulightL.option_chat = "Chat"
	QulightL.option_chat_enable = "Enable"
	QulightL.option_chat_chatbar= "Enable chat bar" 
	QulightL.option_chat_chatframewidth = "Chat width"
	QulightL.option_chat_chatframeheight = "Chat height"
	QulightL.option_chat_editboxwidth = "Editbox width"
	QulightL.option_chat_editboxheight = "Editbox height"
	QulightL.option_chat_tabtextcolor = "Tab text color"
	QulightL.option_chat_ChatFrame = "Позиция чата"
    --buffs
	QulightL.option_buffs = "Buffs/Debuffs"
	QulightL.option_buffs_enable = "Enable"
	QulightL.option_buffs_iconsize = "Buffs size"
	QulightL.option_buffs_iconsizede = "Debuffs size"
	QulightL.option_buffs_timefontsize = "Time font size"
	QulightL.option_buffs_countfontsize = "Count font size" 
	QulightL.option_buffs_spacing = "Buffs spacing" 
	QulightL.option_buffs_debuffspacing = "Debuffs spacing" 
	QulightL.option_buffs_timeYoffset = "timeYoffset" 
	QulightL.option_buffs_BUFFS_PER_ROW = "Buffs per row" 
	QulightL.option_buffs_BUFFpos = "Buffs positions" 
	QulightL.option_buffs_DEBUFFpos = "Debuffs positions" 
	--addonskinning
	QulightL.option_addonsskins = "Addon Skins"
	QulightL.option_addonsskins_DBM = "DBM"
	QulightL.option_addonsskins_PallyPower = "PallyPower" 
	QulightL.option_addonsskins_Skada = "Skada" 
	QulightL.option_addonsskins_Recount = "Recount"
	QulightL.option_addonsskins_Omen = "Omen"
	QulightL.option_addonsskins_KLE = "KLE"	
	QulightL.option_addonsskins_Quartz = "Quartz"		
	QulightL.option_addonsskins_Bigwigs = "Bigwigs"
	QulightL.option_addonsskins_DXE = "DXE"
	QulightL.option_addonsskins_Aurora = "Aurora"
	QulightL.option_addonsskins_CoolLine = "CoolLine"
	--nameplates
	QulightL.option_nameplates = "Nameplates"
	QulightL.option_nameplates_enable  = "Enable"
	QulightL.option_nameplates_showlevel = "Show level"
	QulightL.option_nameplates_width = "Width"
	QulightL.option_nameplates_showhealth = "Show health"
	QulightL.option_nameplates_enhance_threat = "Show threat color"
	QulightL.option_nameplates_combat = "Only in combat"
	QulightL.option_nameplates_good_color = "Good color"
	QulightL.option_nameplates_near_color = "Netral color"
	QulightL.option_nameplates_bad_color = "Bad color"
	QulightL.option_nameplates_goodtransitioncolor = "Good good color"
	QulightL.option_nameplates_badtransitioncolor = "Bad bad color"
	QulightL.option_nameplates_trackccauras = "Show CC debuffs"
	QulightL.option_nameplates_height = "Height"
	QulightL.option_nameplatesad_height = "Health #1"
	QulightL.option_nameplatesad_width = "Width #1"
	QulightL.option_nameplates_show_castbar_name = "Show castbar name"
	QulightL.option_nameplates_health_value = "Show health text"
	QulightL.option_nameplates_name_abbrev = "abbrev"
	QulightL.option_nameplates_healer_icon = "Show healer icon"
	QulightL.option_nameplates_class_icon = "Show class icon"
	QulightL.option_nameplates_track_auras = "Show debuffs"
	QulightL.option_nameplates_auras_size = "Debuffs size"
	
	QulightL.option_Minimap = "Minimap"
	QulightL.option_Minimapenable = "Enable"
	QulightL.option_Minimapminimapsize = "Minimap size"
	QulightL.option_Map = "Map"
	QulightL.option_mapenable = "Enable"
	
	QulightL.option_raidmarker = "Enable Mark Bar"

	
	-- tooltip
	QulightL.option_tooltip = "Tooltip"
	QulightL.option_tooltip_enable = "Enable tooltip"
	QulightL.option_tooltip_hidecombat = "Hide tooltip in combat"
	QulightL.option_tooltip_hidebutton = "Hide tooltip on action bar buttons"
	QulightL.option_tooltip_hideuf = "Hide tooltip on unit frames"
	QulightL.option_tooltip_cursor = "Enable cursor tooltip"
	QulightL.option_tooltip_itemlevel = "Enable Target Item level on tooltip"
	QulightL.option_tooltip_spellid = "Enable Target SpellID on tooltip"
	QulightL.option_tooltip_talents = "Enable Target talents on tooltip"
	QulightL.option_tooltip_title = "Disable show title in tooltip"
	
	-- action bar
	QulightL.option_actionbar = "Action Bars"
	QulightL.option_actionbar_enable = "Enable action bar"
	QulightL.option_actionbar_hotkey = "Show hotkey on buttons"
	QulightL.option_actionbar_hideSTANCE = "Hide Shapeshift bar or Totem bar"
	QulightL.option_actionbar_bottomrows = "Main bars (1-3)"
	QulightL.option_actionbar_rightbars = "Right bar (0-3)"
	QulightL.option_actionbar_splitbar = "Side bars"
	QulightL.option_actionbar_buttonsize = "Size of the main action buttons"
	QulightL.option_actionbar_buttonspacing = "Spacing of the main action buttons"
	QulightL.option_actionbar_petbuttonsize = "Size of the pet action buttons"
	QulightL.option_actionbar_petbuttonspacing = "Spacing of the pet action buttons"
	QulightL.option_actionbar_swaptopbottombar = "Swap top bottom bars"
	QulightL.option_actionbar_macrotext = "Show macros text on buttons"
	QulightL.option_actionbar_verticalshapeshift = "Vertical Shift Bar"
	QulightL.option_actionbar_microbar = "Micro bar"
	QulightL.option_actionbar_mousemicro = "Mouseover for micro bar"
	QulightL.option_actionbar_showgrid = "Always show Grid on action bar"
	QulightL.option_actionbar_mainbarWidth = "MainBar Width(1-12)"
	QulightL.option_actionbar_ownshdbar = "Use an empty bar for shadow dance (rogue) instead of stealth bar"
	QulightL.option_actionbar_lowversion = "Other version for Action Bars"
	QulightL.option_actionbar_sidebarWidth = "SideBar Width(1-6), this option work if Other version for Action Bars = false"
	
	QulightL.option_misk = "Other"
	QulightL.option_raidutility = "Raid Utility"
	QulightL.option_BuffReminderRaidBuffs = "Reminder Raid Buffs"
	QulightL.option_Reminder = "Reminder Solo Buffs"
	QulightL.option_CooldownFlash = "Flashes an icon in the middle of your screen when a cooldown ends."
	QulightL.option_interrupts = "Announce interrupts in /say"
	QulightL.option_AutoScreen = "AutoScreen achievements"
	
	QulightL.option_reset = "Reset"
	QulightL.option_apply = "Apply"
	QulightL.option_close = "Close"
	QulightL.option_setsavedsetttings = "Set settings Per-Character"
	QulightL.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	QulightL.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	QulightL.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	QulightL.option_makeselection = "You must make a selection before you can continue to config."
	
	QulightL.option_bottombars = "Bottom bars:"
	QulightL.option_rightbars = "Right bar(if off then damagebar on)"
	QulightL.option_nameplates_showlevel = "Show level"
	QulightL.option_raidcooldowns = "Raid cooldowns"
	QulightL.option_DamagebarWidth = "Damage bar width(1-12)"
	QulightL.option_Damagebar = "Damage bar"
	QulightL.option_sidebars = "Side bars"